name: PR CD Cleanup
on:
  pull_request_target:
    types: [closed]
jobs:
  close_pr:
    name: Destroy PR deployment
    runs-on: ubuntu-latest
    permissions:
      deployments: write
    env:
      env_name: pr-${{ github.event.pull_request.number }}
    steps:
      - name: Remove Azure Static Webapp
        uses: Azure/static-web-apps-deploy@v1
        continue-on-error: true
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: close
          deployment_environment: ${{ env.env_name }}

      - name: Deactivate GitHub deployment
        uses: chrnorm/deployment-action@v2
        continue-on-error: true
        with:
          ref: ${{ github.github.head_ref }}
          token: ${{ github.token }}
          environment: ${{ env.env_name }}
          transient-environment: true
          initial-status: inactive
